Update CI workflow for UINT256 tests

diff --git a/.github/workflows/uint256-test.yml b/.github/workflows/uint256-test.yml
--- a/.github/workflows/uint256-test.yml
+++ b/.github/workflows/uint256-test.yml
@@ -7,24 +7,46 @@ on:
     branches: [ main ]
   workflow_dispatch:
 
+defaults:
+  run:
+    shell: bash --noprofile --norc -euo pipefail {0}
+
+env:
+  # An envar that signals to tests we are executing in the CI environment
+  CONTINUOUS_INTEGRATION: true
+  # allow overriding Maven command
+  MAVEN: ./mvnw
+  MAVEN_OPTS: "-Xmx512M -XX:+ExitOnOutOfMemoryError"
+  MAVEN_INSTALL_OPTS: "-Xmx3G -XX:+ExitOnOutOfMemoryError"
+  MAVEN_FAST_INSTALL: "-B -V -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all"
+  # Testcontainers kills image pulls if they don't make progress for > 30s and retries for 2m before failing
+  TESTCONTAINERS_PULL_PAUSE_TIMEOUT: 600
+  PTL_TMP_DOWNLOAD_PATH: /tmp/pt_java_downloads
+
+# Cancel previous PR builds.
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
+  cancel-in-progress: true
+
 jobs:
   build-and-test-uint256:
     runs-on: ubuntu-latest
+    timeout-minutes: 60
 
     steps:
       - uses: actions/checkout@v5
         with:
           fetch-depth: 0 # checkout all commits to be able to determine merge base for GIB
-      - uses: actions/setup-java@v5
+      - uses: ./.github/actions/setup
+        timeout-minutes: 10
         with:
-          distribution: 'temurin'
+          cache: 'restore'
           java-version: '24'
-      - name: Cache Maven dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2-
-      - run: |
-          chmod +x ./mvnw ./testing/bin/ptl
-          ./mvnw clean install -DskipTests  -pl '!:trino-docs' > /dev/null 2>&1
+      - name: Maven Install
+        run: |
+          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
+          $MAVEN clean install ${MAVEN_FAST_INSTALL} -pl '!:trino-docs'
+      - name: Run UINT256 Tests
+        run: |
+          chmod +x ./testing/bin/ptl
+          ./testing/bin/ptl test run --environment singlenode-spark-iceberg -- -g uint256
